name: "Rails Unit Tests"

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "doc/**"
      - "**.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "doc/**"
      - "**.md"

jobs:
  build:
    runs-on: "ubuntu-latest"

    timeout-minutes: 15

    strategy:
      matrix:
        ruby: ["2.6", "2.7"]

    services:
      postgres:
        image: "postgres:11"
        env:
          POSTGRES_PASSWORD: "postgres"
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
      memcached:
        image: "memcached"
        ports: ["11211:11211"]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Ruby ${{ matrix.ruby }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          ImageOS: ubuntu18

      - name: "Build and test with Rake"
        env:
          RAILS_TEST_DB_NAME: "postgres"
          RAILS_TEST_DB_USERNAME: "postgres"
          RAILS_TEST_DB_PASSWORD: "postgres"
          RAILS_ENV: "test"
          CI: "true"
          PGDATESTYLE: German
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler --version '~> 2'
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails test
